json.extract! policy,
              :title,
              :description,
              :expert,
              :individual,
              :global,
              :has_changed,
              :version,
              :status,
              :updated_at,
              :created_at