json.max_video_call_rate Expert::MAX_RATE
json.min_video_call_rate Expert::MINIMUM_VIDEO_CALL_RATE
json.min_quick_question_text_rate Expert::MINIMUM_QUICK_QUESTION_TEXT_RATE
json.max_quick_question_text_rate Expert::MAX_RATE
json.min_quick_question_video_rate Expert::MINIMUM_QUICK_QUESTION_VIDEO_RATE
json.max_quick_question_video_rate Expert::MAX_RATE